services:
  bot:
    image: ghcr.io/mistralwz/ministral:latest
    restart: unless-stopped
    volumes:
      - ./config.json:/usr/app/config.json
      - ./data:/usr/app/data
    container_name: skinpeek_bot

